### PR TITLE
update appVersion to latest version

### PR DESCRIPTION
**Pull request by tsahiduek**
controller latest version is 1.0.36 - determined by "appVersion" variable.

### CODE REVIEW

**Comment by tsahiduek** [comment]
@liranp - Can you please review this?

**Comment by liranp** [comment]
@tsahiduek, Please execute `make all` to regenerate the `index.yaml` file and bump to chart version to 1.0.37. Thanks!

**Comment by liranp** [comment]
@tsahiduek Please execute make all to regenerate the index.yaml file and bump the chart version to 1.0.37. Thanks!

**Comment by tsahiduek** [comment]
@liranp 
Done. Please review again.
Thanks!

**Comment by liranp** [comment]
Closing this one; duplicate of #8.

**Pull request closed without merging**
