### PR TITLE
introduce dnsConfig in controller deployment

### PR DESCRIPTION
**Pull request by orong-pp**
allow to configure dnsConfig on the controller deployment
to set dns options like ndots
this reduces the number of dns queries and makes the spotinst controller run less queries on coredns

### CODE REVIEW

**Comment by orong-pp** [comment]
### some details:

**the issue:**
when kubernetes runs a dns query in one of its pods, it first tries to look for the record in its internal namespaces. it can take 4-5 queries that search different options before we actually get to the final answer
in case we query an external website like spot.io we get 4-5 times more queries than we actually need and this puts unwanted load on coredns pods.

the details for this are all explained here
https://dev.to/mrkaran/dns-lookups-in-kubernetes-5cm1

**solution:**
so to deal with this issue one can define the ndots dns configuration option
the default is 5 and it means that only urls with 5 or more dots (.) in it will be queried directly from external dns and not go through 4 redundant dns queries

to set the ndots config option lower I added this pull request and made it possible to control this value and set it lower, so that all queries are direct and no internal search is made

**dnsConfig documentation:**
this is how dnsConfig should be configured according to kubernetes docs
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Review by liranp — APPROVED** [review]

**Comment by liranp** [comment]
Thank you for your contribution, @orong-pp!

**Comment by orong-pp** [comment]
wow! thanks for merging me quickly :)

**Comment by orong-pp** [comment]
wow! thanks for merging me quickly :) @liranp

**Pull request merged**
